### ISSUE TITLE
Problema con Vagrant y Ansible

### ISSUE THREAD

**Issue by germaaan** [IV-GII/GII-2013#137]
No consigo hacer funcionar Ansible con Vagrant, uso este Vagrantfile:

```
Vagrant.configure("2") do |config|
  config.vm.box = "debian"
  config.vm.network :private_network, ip: "192.168.2.50"

  config.vm.provision :ansible do |ansible| 
    ansible.playbook = "playbook.yml"
  end

end
```

Y este playbook:

```

---
- hosts: all
  sudo: yes
  tasks:
    - name: Instalar Nginx
      apt: name=nginx state=present
    - name: Comprobar Nginx
      command: service nginx restart && service nginx status
```

Pero cuando hago `vagrant provision` siempre me aparece el mismo error: 
![eje08_img02](https://f.cloud.github.com/assets/5518719/2021805/49b3e002-8844-11e3-8c20-31185cc694a5.png)

Se ve que no encuentra el archivo de inventario, en la documentación de Vagrant pone que no es necesario indicarlo, pero aún así, si lo indico con "ansible.inventory_path" el error es el mismo. Además también he comprobado que la máquina es accesible directamente por SSH usando el nombre de usuario y contraseña "vagrant".
